backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = "main-login";

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\PaymentCourse;
use frontend\models\Profile;
use frontend\models\Order;
use frontend\models\Orderitem;
use frontend\models\Orderpayment;

//Backend
use backend\models\Category;
use backend\models\Course;
use backend\models\Instructor;

//Mercado Pago
use MercadoPago\SDK;
use MercadoPago\Payment;
use MercadoPago\Payer;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $categories = Category::find()->where(['categoryparent_id' => null,'estatus' => 'active'])->all();
        return $this->render('index',['categories'=>$categories]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post())) {

            if($model->saveContact()){
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            }else{
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }
            
            /*if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }*/

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    //Show popup Course detail
    public function actionCourse(){
        $idCourse = Yii::$app->request->get()["id"];
        $model    = Course::find()->where(["course_id" => $idCourse])->one();
        return $this->renderAjax('modalPopup', [
            'model' => $model,
        ]);
    }

    //Show popup Instructor Detail
    public function actionInstructor(){
        $idInstructor = Yii::$app->request->get()["id"];
        $model        = Instructor::find()->where(["instructor_id" => $idInstructor])->one();
        return $this->renderAjax('modalPopupInstructor', [
            'model' => $model,
        ]);
    }


    //Form to Pay Course
    public function actionInscription(){
        $idCourse = Yii::$app->request->get();
        if(isset($idCourse["id"])){
            $model        = Course::findOne(['course_id'=>$idCourse]);
            $modelPayment = new PaymentCourse();
            //$modelPayment->acceptconditions = 0;
            return $this->render('paymentcourse',[
                    'model'        => $model,
                    'modelPayment' => $modelPayment
                ]);
        }else{
            return $this->redirect(['index']);
        }
    }//end function

    //Create Payment Course (Mercado Pago)
    public function actionCreatepayment(){
        $paymentCourse   = Yii::$app->request->post()["PaymentCourse"];
        $mp_issuer       = Yii::$app->request->post()["issuer"];
        $mp_installments = Yii::$app->request->post()["installments"];
        $mp_token        = Yii::$app->request->post()["token"];
        $access_token    = Yii::$app->params["mercadopago"]["dev"]["seller"]["test_access_token"];

        /**
         * Save Client Info in Profile Table
         */
        $profileModel            = new Profile();
        $profileModel->firstname = $paymentCourse["namepayment"];
        $profileModel->lastname  = $paymentCourse["lastnamepayment"];
        $profileModel->email     = $paymentCourse["email"];
        $profileModel->phone     = $paymentCourse["phonepayment"];

        if($profileModel->validate()){
            //save
            $profileModel->save();
        }else{
            //return error
            echo "<pre>";
            var_dump($profileModel->errors);
            echo "</pre>";
            die();
        }//end if

        /**
         * Save Order
         */
        $orderModel                 = new Order();
        $orderModel->profile_id     = $profileModel->profile_id;
        $orderModel->payment_method = "on_line";
        $orderModel->status         = "pending";
        $orderModel->creation_date  = date("Y-m-d H:i:s");
        $orderModel->payment_type   = "";
        if($orderModel->validate()){
            //save
            $orderModel->save();
        }else{
            //return error
            echo "<pre>";
            var_dump($orderModel->errors);
            echo "</pre>";
        }

        /**
         * Save Order
         */
        $modelCourse = Course::find()->where(["course_id" => $paymentCourse["courseId"]])->one();
        $coursename  = $modelCourse->title == 'basico' ? 'Básico' : 'Avanzado';

        $orderItemModel              = new Orderitem();
        $orderItemModel->order_id    = $orderModel->order_id;
        $orderItemModel->product_id  = $modelCourse->course_id;
        $orderItemModel->typeproduct = "course";
        $orderItemModel->sku         = $modelCourse->code;
        $orderItemModel->name        = $modelCourse->category->name." - ".$coursename;
        $orderItemModel->price       = $modelCourse->price;
        $orderItemModel->quantity    = 1;

        if($orderItemModel->validate()){
            $orderItemModel->save();
        }else{
            //return error
            echo "<pre>";
            var_dump($orderItemModel->errors);
            echo "</pre>";
        }//end if


        /**
         * Create a payment referene (save in server side)
         * @var external_reference for indentification paymente in server side
         */
        $external_reference = $profileModel->profile_id."|".$orderModel->order_id."|".$orderItemModel->sku;

        //Mercado Pago SDK
        $mp           = new SDK();
        $mp->initialize();
        $config = $mp->config();
        $config->set('ACCESS_TOKEN', $access_token);
        //$mp::setAccessToken($access_token);

        //Mercado Pago Payment Information
        $payment                     = new Payment();
        $payment->transaction_amount = (float) $paymentCourse["transactionAmount"];
        $payment->token              = $mp_token;
        $payment->description        = $paymentCourse["description"];
        $payment->installments       = (int) $mp_installments;
        $payment->payment_method_id  = $paymentCourse["paymentMethodId"];
        $payment->issuer_id          = (int) $mp_issuer;
        $payment->external_reference = $external_reference;

        //Mercado Pago Payer Information
        $payer             = new Payer();
        $payer->email      = $paymentCourse["email"];
        $payer->first_name = $paymentCourse["namepayment"];
        $payer->last_name  = $paymentCourse["lastnamepayment"];

        $payment->payer = $payer;

        try {

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
//use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'reCaptcha')->widget(\kekaadrenalin\recaptcha3\ReCaptchaWidget::class) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="container">
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container-fluid site-login-wrap ">
    <main role="main" class="container site-login-container d-flex align-items-center">
        <div class="d-flex justify-content-center">
            <div class="col-12 col-lg-5">
                <!-- <h1><?//= Html::encode($this->title) ?></h1>
                <p>Please fill out the following fields to login:</p> -->

                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                            <?= $form->field($model, 'username')->textInput(['placeholder'=>'Nombre de usuario'])->label(false) ?>

                            <?= $form->field($model, 'password',['options'=>['class'=>'mt-5']])->passwordInput(['placeholder'=>'Contraseña'])->label(false) ?>

                            <?//= $form->field($model, 'rememberMe')->checkbox() ?>

                            <!-- <div style="color:#999;margin:1em 0">
                                If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                                <br>
                                Need new verification email? <?= Html::a('Resend', ['site/resend-verification-email']) ?>
                            </div> -->

                            <div class="form-group text-center">
                                <?= Html::submitButton('Iniciar Sesión', ['class' => 'btn btn-light mt-5', 'name' => 'login-button']) ?>
                            </div>

                            <div class="pt-5">
                                <div class="text-center pb-3">
                                    O ¿Has olvidado tu contraseña?
                                </div>
                                <div class="text-center pt-2">
                                    ¿No tienes una cuenta? <strong>Regístrate</strong>
                                </div>
                            </div>

                        <?php ActiveForm::end(); ?>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

frontend/views/site/modalPopup.php
<?php 
//use Yii;
use yii\helpers\Html;
use yii\helpers\Url;

echo newerton\fancybox3\FancyBox::widget([
    'target' => '.data-fancybox-instructor'
]);

?>
<div id="modal-basic" class="col-xl-7 col-lg-8 col-md-9 col-sm-9">
    <div class="container-fluid">
    	<?php 
    	//category
		$categoryName = $model->category->name;

		//course
        $courseId        = $model->course_id;
        $courseType      = ($model->title == 'basico' ? 'Básico' : 'Avanzado') ;
        $courseIntro     = $model->introduction;
        $courseVideo     = explode("/", $model->videointro);
        $codeVideo       = $courseVideo[3];
        $courseTopics    = $model->topics;
        $courseMaterials = $model->materials;

		//instructor
        $instructorId   = $model->instructor->instructor_id;
        $instructorName = $model->instructor->firstname." ".$model->instructor->lastname;
        $instructorImg  = $model->instructor->perfilimage;

        //whatsapp
        $numberWa = "521234567890";
        $urltext = urlencode("Estoy interesado en inscribirme de forma semipresencial al curso de : ".$categoryName." - ".$courseType.", impartido por : ".$instructorName.".");
    	?>
        <div class="row">
            <div class="col-md-8 col-12">
                <div class="modal-title">
                    <?php echo $categoryName; ?>
                </div>
                <div class="float-right modal-type">
                	Curso : <?php echo $courseType; ?>
                </div>
                <div class="clearfix"></div>
                <div class="modal-subtitle">
                	<?php echo $courseIntro; ?>
                </div>
                <div class="modal-video embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://player.vimeo.com/video/<?php echo $codeVideo; ?>?title=0&byline=0&portrait=0" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-md-4 col-12">
                <div class="row modal-basic-instructor">
                    <div class="col-5 modal-basic-instructor-picture">
                        <?= Html::img(Url::base().'/backend/web/'.$instructorImg, ['class' => 'img-fluid']); ?>
                    </div>
                    <div class="col-7 modal-basic-instructor-name">
                        <div class="modal-basic-instructor-name-title" class="col-12">Instructor</div>
                        <div class="modal-basic-instructor-name-subtitle" class="col-12"><?php echo $instructorName; ?></div>
                        <div class="row">
                            <div class="col-12">
                                <button class="btn btn-modal col-12 data-fancybox-instructor" data-type="ajax" data-src="<?php echo Url::to(['site/instructor','id'=>$instructorId]) ?>" data-touch="false">
                                    Ver Información
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row modal-details">
                    <div class="col-4" style="margin-bottom: 15px; margin-top: -15px;">
                        <div style="background-color: #072879; width: 2px; height: 100%; padding-bottom: 25px; margin-left: 60%;"></div>
                    </div>
                    <div class="col-8 modal-details-item">
                        <div class="row">
                            <div class="col-4 modal-details-item-img">
                              <?= Html::img('@web/images/icon-temario.png', ['class' => 'img-fluid']); ?>  
                            </div>
                            <div class="col-8 modal-details-item-title mt-1">
                                Temario
                            </div>
                            <div class="col-12 modal-details-item-detail">
                            	<?php echo $courseTopics; ?>
                            </div>
                            <div class="col-4 modal-details-item-img">
                              <?= Html::img('@web/images/icon-materiales.png', ['class' => 'img-fluid']); ?>  
                            </div>
                            <div class="col-8 modal-details-item-title mt-1">
                                Materiales
                            </div>
                            <div class="col-12 modal-details-item-detail">
                                <?php echo $courseMaterials; ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="row">
                            <div class="col-sm-12 col-md-5">
                                <!-- <a class="btn btn-modal col-12" >En Línea</a> -->
                                <?= Html::a("En Línea", $url = Url::to(['cursos/inscripcion/','id'=>$courseId]), ['class' => 'btn btn-modal col-12'] )
                                /*Html::a(
                                        "En Línea", 
                                        ['/site/paymentcourse'], 
                                        [
                                            'class' => 'btn btn-modal col-12',
                                            'data'=>[
                                                'method' => 'post',
                                                'params' => ['id' => $courseId]
                                            ]
                                        ]);*/
                                 ?>
                            </div>
                            <div class="col-sm-12 col-md-7">
                                <a class="btn btn-modal col-12" target="_blank" href="https://wa.me/<?php echo $numberWa; ?>/?text=<?php echo $urltext ?>">Semipresencial</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/site/modalPopupInstructor.php
<?php 
//use Yii;
use yii\helpers\Html;
use yii\helpers\Url;

$ins_name       = $model->firstname." ".$model->lastname;
$ins_trajectory = $model->trajectory;
$ins_perfilimg  = $model->perfilimage;
$ins_fb         = $model->fblink;
$ins_ig         = $model->iglink;
$ins_wp         = $model->wplink;

$ins_image1     = $model->image1;
$ins_image2     = $model->image2;
$ins_image3     = $model->image3;
$ins_image4     = $model->image4;

$show_gallery = false;
if(!empty($ins_image1) && !empty($ins_image2) && !empty($ins_image3) && !empty($ins_image4)){
    $show_gallery = true;
}//end if

?>

<!-- Modals PopUp -->
<div id="modal-instructor" class="col-xl-7 col-lg-8 col-md-9 col-sm-9">
    <div class="container-fluid">
        <div class="row">
            <div class="<?php echo $show_gallery == true ? "col-md-6" : "" ?> col-12">
                <div class="row modal-instructor-head">
                    <div class="col-4">
                        <?= Html::img(Url::base().'/backend/web/'.$ins_perfilimg, ['class' => 'img-fluid']); ?>
                    </div>
                    <div class="col-8">
                        <div class="modal-instructor-title">Instructor</div>
                        <div class="modal-instructor-subtitle"><?php echo $ins_name; ?></div>
                    </div>
                </div>
                <div class="row modal-instructor-detail">
                    <div class="col-12">
                        <div class="modal-instructor-detail-title">
                            Trayectoria
                        </div>
                        <div class="modal-instructor-detail-text">
                            <?php echo nl2br($ins_trajectory) ?>
                        </div>
                    </div>
                </div>
                <div class="row modal-instructor-share">
                    <div class="col-12">
                        <div class="modal-instructor-share-title">
                            Redes Sociales
                        </div>
                    </div>
                    <div class="row modal-instructor-share-icons">
                        <div class="col-4">
                            <?php 
                            if(!empty($ins_ig))
                                echo Html::a(Html::img('@web/images/ig-icon.svg',['class'=>'img-fluid','style'=>'width: 35px; height: auto;']), $url = $ins_ig ,['title'=>'Instagram','target'=>'_blank']) 
                            ?>
                        </div>
                        <div class="col-4">
                            <?php 
                            if(!empty($ins_wp))
                                echo Html::a(Html::img('@web/images/wa-icon.svg',['class'=>'img-fluid','style'=>'width: 35px; height: auto;']),$url = "https://wa.me/52".$ins_wp, ['title'=>'whatsapp','target'=>'_blank']) 
                            ?>
                        </div>
                        <div class="col-4">
                            <?php 
                            if(!empty($ins_fb))
                                echo Html::a(Html::img('@web/images/fb-icon.svg',['class'=>'img-fluid','style'=>'width: 35px; height: auto;']),$url = $ins_fb,['title'=>'facebook','target'=>'_blank']) 
                            ?>
                        </div>
                    </div>
                </div>                
            </div>

            <?php 
            if ($show_gallery == true) {
            ?>
            <div class="col-md-6 col-12">
                <div class="row">
                    <div class="col-6">
                        <?= Html::img(Url::base().'/backend/web/'.$ins_image1, ['class' => 'img-fluid modal-instructor-gallery']); ?>
                        <?= Html::img(Url::base().'/backend/web/'.$ins_image4, ['class' => 'img-fluid modal-instructor-gallery']); ?>
                    </div>
                    <div class="col-6">
                        <?= Html::img(Url::base().'/backend/web/'.$ins_image2, ['class' => 'img-fluid modal-instructor-gallery']); ?>
                        <?= Html::img(Url::base().'/backend/web/'.$ins_image3, ['class' => 'img-fluid modal-instructor-gallery']); ?>
                    </div>
                </div>
            </div>
            <?php 
            }//end if
            ?>
        </div>
    </div>
</div>
<!-- End Modals PopUp -->

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Resend verification email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A verification email will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>